#from datetime import datetime
#from baseDatos.serializador import Serializador
#from Restaurante import *
#from Personas import *

class Administrador (Menu):
	if __name__ == __main__:
		gestor = Gestor()
    	restaurante = gestor.getRestaurante()
    	restaurante.setClientes(gestor.getClientes())
    	restaurante.setEmpleados(gestor.getEmpleados())
    	restaurante.setMesas(gestor.getMesas())
    	restaurante.setEmpleadoDelMes(gestor.getEmpleadoDelMes())
    	restaurante.setInventario(gestor.getInventario())
    	restaurante.setPedidos(gestor.getPedidos())
	
    	#Crear un objeto Financia 
        financia = Financia(restaurante)  	
    	
    	menu = Menu.crearMenu()
    	res = Material(Material.Tipo.RES, 100, 100)
    	especias = Material(Material.Tipo.ESPECIAS, 100, 50)
    	aceites = Material(Material.Tipo.ACEITES, 100, 100)
    	pollos = Material(Material.Tipo.POLLOS, 100, 200)
    	vinos = Material(Material.Tipo.VINOS, 100, 300)
    	cebollas = Material(Material.Tipo.CEBOLLAS, 100, 50)
    	champinones = Material(Material.Tipo.CHAMPINONES, 500, 100)
    	ajos = Material(Material.Tipo.AJOS, 100, 30)
    	tomates = Material(Material.Tipo.TOMATES, 400, 200)
    	quesos = Material(Material.Tipo.QUESOS, 300, 150)
    	cerdos = Material(Material.Tipo.CERDOS, 100, 200)
    	atun = Material(Material.Tipo.ATUN, 100, 250)
    	panes = Material(Material.Tipo.PANES, 200, 50)
    	pescados = Material(Material.Tipo.PESCADOS ,200 ,300 )
    	papas = Material(Material.Tipo.PAPAS ,200 ,100 )
    	huevos = Material(Material.Tipo.PAPAS ,200 ,100 )
    	    	// Crear turnos
    	turno1 = Turno(Turno.Tipo.SEMANA, 2.0, 50000)
    	turno2 = Turno(Turno.Tipo.SEMANA, 8.0, 60000)
    	turno3 = Turno(Turno.Tipo.SEMANA, 2.0, 70000)
    	turno4 = Turno(Turno.Tipo.DOMINGO, 8.0, 55000)
    	turno5 = Turno(Turno.Tipo.SEMANA, 2.0, 65000)
    	turno6 = Turno(Turno.Tipo.SEMANA, 8.0, 75000)
    	turno7 = Turno(Turno.Tipo.SEMANA, 2.0, 60000)
    	turno8 = Turno(Turno.Tipo.SEMANA, 8.0, 70000)
    	turno9 = Turno(Turno.Tipo.SEMANA, 2.0, 80000)
    	turno10 = Turno(Turno.Tipo.SEMANA, 8.0, 65000)
    	turno11 = Turno(Turno.Tipo.SEMANA, 3.0, 80000)
    	turno12 = Turno(Turno.Tipo.SABADO, 7.0, 50000)
    	turno13 = Turno(Turno.Tipo.SABADO, 3.0, 60000)
    	turno14 = Turno(Turno.Tipo.SEMANA, 7.0, 70000)
    	turno15 = Turno(Turno.Tipo.SEMANA, 2.0, 55000)
    	turno16 = Turno(Turno.Tipo.DOMINGO, 3.0, 55000)
    	turno17 = Turno(Turno.Tipo.SABADO, 2.0, 55000)
	    
        #Crear empleados
    	empleado1 = Mesero("Juan", 123456789L, "mesero", restaurante, turno1)
    	empleado1.agregarTurno(turno2)
    	empleado2 = Cocinero("Fernando", 234567891L, "cocinero", restaurante, turno2)
    	empleado2.agregarTurno(turno3)
    	empleado3 = Domiciliario("Santiago", 345678912L, "domiciliario", restaurante, turno4)
    	empleado1.agregarTurno(turno5)
    	empleado4 = Mesero("Jhon", 123456789L, "mesero", restaurante, turno6)
    	empleado1.agregarTurno(turno7)
    	empleado5 = Cocinero("Moises", 234567891L, "cocinero", restaurante, turno8)
    	empleado2.agregarTurno(turno9)
    	empleado6 = Domiciliario("Rigo", 345678912L, "domiciliario", restaurante, turno10)
    	empleado1.agregarTurno(turno11)
    	empleado7 = Mesero("Brayan", 123456789L, "mesero", restaurante, turno12)
    	empleado1.agregarTurno(turno13)
    	empleado8 = Cocinero("Felipe", 234567891L, "cocinero", restaurante, turno14)
    	empleado2.agregarTurno(turno15)
    	empleado9 = Domiciliario("Martin", 345678912L, "domiciliario", restaurante, turno16)
    	empleado1.agregarTurno(turno17)

    	pedido = Pedido()
        plato = Plato()
		for mesa1 in restaurante.getMesas()
			mesa1.anadirNumero(mesa1.getNumeroMesa())
		restaurante.borrarReservasViejas()